#!/usr/bin/env ruby
require 'highline/import'
Dir["./app/**/*.rb"].each { |f| require f }

def admin_menu
  say("Administrator Panel\n" +
      "Please choose from the following:\n" +
      "1. Add a new question\n" +
      "2. Edit an existing question\n" +
      "3. Delete a question\n" +
      "4. See a list of all current questions\n" +
      "5. Return to main menu\n")
end


ARGV_ERROR = <<EOS
run with './flash_cards'
EOS

MENU_ERROR = <<EOS
I did not recognize that. Please try again.
EOS

if ARGV.length == 0
  choose do |menu|
    menu.header = "Welcome to Flashcards!\n" + "Please choose from the following:\n"
    menu.choice("Play a new game") { say("you chose a")}
    menu.choice("View score dashboard") { say("you chose b")}
    menu.choice("Review missed questions") { say("you chose c")}
    menu.choice("Administrator activities") { admin_menu }
    menu.choice("Exit") { say("you chose to exit") }
  end
else
  print ARGV_ERROR
  exit
end
